version: 2

sphinx:
  configuration: source/conf.py

formats: all

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-20.04
  tools:
    python: "3.13"
  apt_packages:
    - libgraphviz-dev